FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

RUN apt-get update && apt-get install -y \
    build-essential \
    zlib1g-dev \
    libncurses5-dev \
    libgdbm-dev \
    libnss3-dev \
    libssl-dev \
    libsqlite3-dev \
    libreadline-dev \
    libffi-dev \
    wget \
    libbz2-dev \
    libjpeg-dev \
    musl-dev

RUN wget https://www.python.org/ftp/python/3.7.5/Python-3.7.5.tgz && \
    tar -xf Python-3.7.5.tgz && \
    cd Python-3.7.5 && \
    ./configure --enable-optimizations && \
    make -j$(nproc) && \
    make altinstall

#RUN apt-get install -y gcc-5
#RUN apt-get install -y python3.7
#RUN apt-get install -y python3-pip
RUN apt-get -y install git
RUN apt-get -y install sed

COPY requirements.txt /tmp/requirements.txt
RUN pip3.7 install -r /tmp/requirements.txt