FROM nvcr.io/nvidia/tensorflow:20.12-tf1-py3

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

RUN apt-get update && apt-get install -y \
    build-essential \
    zlib1g-dev \
    libncurses5-dev \
    libgdbm-dev \
    libnss3-dev \
    libssl-dev \
    libsqlite3-dev \
    libreadline-dev \
    libffi-dev \
    wget \
    libbz2-dev \
    libjpeg-dev \
    liblzma-dev \
    musl-dev

# RUN wget https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tgz && \
#     tar -xf Python-3.8.1.tgz && \
#     cd Python-3.8.1 && \
#     ./configure --enable-optimizations && \
#     make -j$(nproc) && \
#     make altinstall

#RUN apt-get install -y gcc-5
#RUN apt-get install -y python3.7
#RUN apt-get install -y python3-pip
RUN apt-get -y install git
RUN apt-get -y install sed

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

#COPY pointnet2_pyt /tmp/pointnet2_pyt
#RUN cd /tmp/pointnet2_pyt && pip3.7 install -e . && cd ..
